### ISSUE TITLE
Solo play - Basic automation

### ISSUE THREAD

**Issue by mmeldo** [townteki/townsquare#1218]
- [x] #1268
  - [x] clean unnecessary functions
- [x] #1269
- [x] Game Engine updates
  - [x] #1278
  - [x] #1279
    - does not use Play Window class, but own implementation
  - [x] #1280
  - [x] #1281
  - [x] Shootout Phase for Solo play
    - [x] #1295
    - [x] #1302
    - [x] #1296
  - [x] #1282
  - [x] #1283
- [x] #1331
  - update Automaton funcitons that were just copied over from `Player` class
- [x] POC: #1291
  - [x] `MenuPrompt`
  - [x] `ValuePrompt`
  - [x] `ChooseYesNoPrompt`
  - [x] `SelectCardPrompt`
- [x] UI - option for Solo play when starting game
  - [x] townteki/townsquare-client#100
  - [x] POC: townteki/townsquare-client#101
  - [x] Add proposed Solo deck as standalone and choose it by default
- [x] Decision engine
  - [x] Making plays
  - [x] Ending Phases
  - [x] #1310
  - [x] #1332
  - [x] Shootout hands
  - [x] Gunfighter archetype
    - [x] #1298
    - [x] #1325
      - [x] Building Deeds
      - [x] Call outs
      - [x] Discards
      - [x] Fleeing
      - [x] Jobs
      - [x] Posse Formation
      - [x] Reacts
      - [x] Sidekicks 
      - [x] #1342
    - [x] Automaton pulls
      - [x] #1313
      - [x] #1314
      - [x] #1315
      - [x] #1316
      - [x] #1317
      - [x] #1334
    - [x] Target priorities
      - [x] Dudes leaving play/control
      - [x] Opposing mark
      - [x] #1324
- [x] #1297
- [x] #1333
- [ ] Testing

__Notes:__
- need better rules for discarding for upkeep (ratio upkeep/influence)
