### ISSUE TITLE
Update cards from new core set

### ISSUE THREAD

**Issue by mmeldo** [townteki/townsquare#1343]
Some of cards final version is different from what it was initially, so they need to be updated.
- [x] Saved By Grace
- [x] Deadwood Miner's Alliance - boot should be a cost, not a target
- [x] Sun in Yer Eyes
- [x] Ol' Fashioned Hangin' - opposing dude, not just any
- [x] Kidnappin' - bounty should go to all dudes that join during job
- [x] Meet the New Boss
- [x] Xemo's Turban - maybe update to make pull a cost
- [x] Miranda Clarke
- [x] The Mixer - test it, not sure it works as intended
- [x] Lane Healey
- [x] Jim Hexter - use limit parameter
- [x] Shi Long Peng - he should not have any ability
- [x] Update Tokens
