### ISSUE TITLE
Nitpicky stuff (3/2022)

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1411]
- [ ] **Baker Andrews**
If the player's hand is legal, he should not get a bounty for using the ability.

- [x] **Bass Reeves**
Log miscounts, so it has messages like "Player's rank is increased by 1 thanks to the 9"

- [x] **Laura Banks**
Log message appears twice, one of which is unfinished. It's like the log is stuttering.

- [x] **Quickdraw Handgun**
The WW edition is slightly different in that it makes the donated hand legal instead of preventing punish. (Affects [Martyr's Cry](https://dtdb.co/en/card/12020) and [Turtle's Guard](https://dtdb.co/en/card/14029))

- [x] **Putting The Pieces Together**
Inexplicably, revealing a cheatin' hand does not cause this to boot.

- [ ] **Full Moon Brotherhood**
Using the ability on someone with a goods attached causes the target's goods to fall off later. (Probably during nightfall, we didn't quite pin it down.)

- [ ] **Smith & Robards Trade Show**+**Auto-Gatling**
Attaching Auto-Gatling to an opponent's deed, then booting it with S&RTS has the resulting CP count double in the total.

**Comment by mmeldo** [comment]
`Full Moon Brotherhood` - do you know exactly for which dude and goods this happened? Because losing the trait could have caused the good attachment to be invalid.

**Comment by PesiTheWizard** [comment]
One was The Caretaker with a Buffalo Rifle, one was Monte Bank on I-don't-remember-who. At any rate, it didn't seem relevant, and if this was the case, should have lost the goods immediately and not later.

**Comment by PesiTheWizard** [comment]
The Full Moon Brotherhood "goods fall off"-thing happens after nightfall, at the same time as it switches over to a new day.

PS. The new Quickdraw handgun is 'legalizing' the wrong hand.

**Comment by PesiTheWizard** [comment]
RE: Auto-gatling

There is also an extra CP that happens if Technological Exhibition marking Town Square puts an Auto-Gatling on a deed owned by the opponent. (Haven't tested other improvements)
Dragging the improvement to the discard brought the CP-count back to normal.
