### ISSUE TITLE
Nitpicky stuff (4/2022)

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1426]
- [x] [Morgan Stables](https://dtdb.co/en/card/11003) can react on opponent's dudes being moved by you, should not.
- [x] [Cookin' Up Trouble](https://dtdb.co/en/card/07019) can discard things with cheatin' punishment abilities.
- [ ] [De Annulos Mysteriis](https://dtdb.co/en/card/18030) is not restricted to a job marking a location.
- [x] git - Funtime Freddy is in the wrong folder
- [x] High Stakes Haven offers discard option when no cards are in play hand as long as GR available. (And could use passing false to DiscardAtRandom now that that's a thing)
- [x] [Christine Perfect](https://dtdb.co/en/card/18014) consistantly can't find a legal target for the noon ability
- [x] The Flying Popescus not getting the inf bonus despite hex attachments (possibly because 'hex' isn't an array)

**Comment by mmeldo** [comment]
Re [De Annulos Mysteriis](https://dtdb.co/en/card/18030): the location restriction was not done because it would be quite complicated and is not really worth it.

**Comment by mmeldo** [comment]
Closing since I am not going to the change for De Annulos Mysteriis. In case there will more such cards targeting jobs marking specific targets, it can be implemented.
