### ISSUE TITLE
Nitpicky stuff (8/2022)

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1467]
- [x] **[Disgenuine Currency Press](https://dtdb.co/en/card/11016)**
Owner doesn't draw a card when it leaves play

- [x] **[Heath's Curiosity Shoppe](https://dtdb.co/en/card/23031)**
Allows the discarding of only 1 card

- [x] **[Funtime Freddy](https://dtdb.co/en/card/06001)**
Allows the finding of only 1 hex

- [x] **[Fannin' the Hammer](https://dtdb.co/en/card/22051)**
Coded according to dtdb text, card text is the correct version

- [x] **[Nickel Night Inn](https://dtdb.co/en/card/18022)**
Allows the picking of illegal targets because the gameAction entry is mistyped

- [x] **[Faster on the Draw](https://dtdb.co/en/card/05037)**
Can pick opposing dudes for the +bullets, second target is optional

- [x] **[Silent Sigil](https://dtdb.co/en/card/14021)**
Usable only if cards drawn, should be usable with any hand size

- [x] Unopposed job-posse doesn't visit the mark.
Affects Quarter Horse which has the rider stay at their original location and Tummy Twister which doesn't reattach

- [ ] Softlock during lowball if total cards in deck+discard is less than 5

Addendum:
- [x]  **[The Mayor's Office](https://dtdb.co/en/card/04012)**
Targeting is entirely blocked if either action is illegal, such as from [Fancy New Hat](https://dtdb.co/en/card/06016)

**Comment by mmeldo** [comment]
- Can you please give more details about the problem with `Disgeniune Currency Press` ?
- what do you mean exactly with the `second target is optional` for the `Faster on the Draw` ? is there some problem with it? 
- regarding the unopposed jobs - are we sure that is the case? to implement this, I followed this document on dtdb: http://dtdb.co/en/structure and based on this, leader posse moves to the mark only if there is someone opposing.

**Comment by PesiTheWizard** [comment]
- ![DCP_demonstrationOfNonfunctionality](https://user-images.githubusercontent.com/26526269/188148410-a4ad9672-12fc-4c2e-997d-cca03bac07a8.png) It just doesn't draw. I suspect the traitReaction needs to work from discard.
- When it comes to selecting a second target, the user can just... not. No judgment is rendered on why they would to this, hence why it's under "nitpicky stuff". (I'd have both targets in the targeting clause)
- I asked about Quarter Horse and being unopposed in the discord rules channel, but it must have gone to the winds in the recent move. The answer I got was that they stayed put at the mark, the implication being that the entire posse moves there before going home.

**Comment by mmeldo** [comment]
well, most other things reported here are genuine bugs, not just a nitpicky stuff. but this with the FotD, it really nitpicky. if it would be just simple change, I guess I could change it. But as it is, I will leave it as it is. If you want to open a separate bugs, feel free.

**Comment by mmeldo** [comment]
the other problem with moving posse when unopposed, I guess I will check again with the rules team.

**Comment by mmeldo** [comment]
Note: fix the whole sequence of posses forming and moving for jobs according to new rules.

**Comment by mmeldo** [comment]
> Softlock during lowball if total cards in deck+discard is less than 5

By softlock you mean that game does not allow you to continue because there is not enough cards in draw deck?

**Comment by PesiTheWizard** [comment]
> By softlock you mean that game does not allow you to continue because there is not enough cards in draw deck?

Yep. It wants 5 cards during gambling.
