### ISSUE TITLE
Nitpicky stuff (9/2022)

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1488]
- [ ] [Disingenuine Currency Press](https://dtdb.co/en/card/24152)
Owner doesn't draw when it is discarded from play.

- [ ] [Nickel Night Inn](https://dtdb.co/en/card/18022)
Can select already-booted dudes to boot.

- ~~[Takin' Ya With Me](https://dtdb.co/en/card/01140)~~
It shouldn't have its own seperate step for taking the 1 casualty.

- [ ] [Lawrence Blackwood](https://dtdb.co/en/card/01037)
Can use his ability in town square.

- [ ] [Notary Public](https://dtdb.co/en/card/14016)
Can boot itself if it is government/public,
The movement ability doesn't keep you from picking dudes that can't move.

- [ ] [Crystal Palace](https://dtdb.co/en/card/22034)
Works only for the controller.

- [ ] [Mount Moriah Cemetery](https://dtdb.co/en/card/24120)
Discount only ever provided to owner of deed (According to my tests).

- ~~[Cheyenne Club](https://dtdb.co/en/card/23034)~~
Can pick unskilled dudes, doing nothing.

**Comment by mmeldo** [comment]
First, some things I am not sure what you mean, did not reproduce, or I do not think are a problem
- [Takin' Ya With Me](https://dtdb.co/en/card/01140) - why not?
- [Notary Public](https://dtdb.co/en/card/14016) - did not reproduce the self-booting
- [Cheyenne Club](https://dtdb.co/en/card/23034) - doing nothing is exactly what it should do since those dudes are unskilled
- > When 2 different things "have to be chosen as first casualty", the game just force-picks one of them.
I'm given to understand either can be first casualty.

I am aware of that, but I plan to redo the whole casualty taking step and properly do a first casualties. I will add this to the issue I have opened for that: #207

**Comment by PesiTheWizard** [comment]
>     * Notary Public - did not reproduce the self-booting
It needs to become either public or government, like from [Legal Instruments](https://dtdb.co/en/card/06013)

>     * Cheyenne Club - doing nothing is exactly what it should do since those dudes are unskilled
I would think such dudes were not valid picks under the "actions must affect the game state"-clause

**Comment by mmeldo** [comment]
__RE:__ Cheyenne club - but it does change the state, those dudes still have +1 to their skills, but they do not have any skill keyword to show it. But if anything would give them the keyword (e.g. Prayer), then they would have +1 blessed.

__RE:__ Notary Public: did not realize it can be given government deed. but this one is really nitpicking :)

I decided to create new issues for things that are proper bugs and leave here only those from the nitpicking category.

**Comment by mmeldo** [comment]
RE: [Takin' Ya With Me](https://dtdb.co/en/card/01140) - I did a quick test and when the additional casualty step is taken away, it is even worse. I knew I put it there for something. To fix this would be too difficult considering I plan to change the casualty step anyway. The `Takin' Ya With Me` is already mentioned in the #207 so it will be fixed with that update.
