### ISSUE TITLE
Nitpicky stuff (10/2022)

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1517]
- [x] [Bio-Charged Neutralizer](https://dtdb.co/en/card/24176)2
Can pick its own parent as recepient

- [x] Disgenuine Currency Press
Trait not triggered when parent discarded

- [x] [Rosenbaum's Golem](https://dtdb.co/en/card/19010)
Doing the disarm thing: unbooting only triggers if value was increased

- [x] [Hellstromme Plant #9](https://dtdb.co/en/card/19026)
In a shootout, can target non-participating things

- [x] [Magnum Opus Tenebri](https://dtdb.co/en/card/21044)
Can somehow target dudes outside of the shootout,
No message on basic use(callback in the options-slot?),
Can ace opposing abominations to ace the target

- [x] [Hiding in the Shadows](https://dtdb.co/en/card/01118)
Can target opposing dudes.

- [x] [108 Gracious Gifts](https://dtdb.co/en/card/24001)
Can select already-unbooted dudes to unboot (intentional?)

- [x] [Ivor Hawley (Exp.1)](https://dtdb.co/en/card/10011)
Discount only looks at your own abominations

- [x] [Enapay](https://dtdb.co/en/card/10008)
Can give himself the +1 influence

- [x] [Fire of Nanahbozho](https://dtdb.co/en/card/24210)
Spell action is missing the deed requirement

- [x] [Epidemic Laboratory](https://dtdb.co/en/card/14019)
Job leader doesn't have to be skilled despite the leaderCondition

- [x] takeyerlumpsprompt.js
Message needs an "s" after the action variable

**Comment by mmeldo** [comment]
> No message on basic use(callback in the options-slot?)

@PesiTheWizard what do you mean by this?

**Comment by mmeldo** [comment]
ok, I see what you mean 😄 as usual noticed just after I wrote the message
